name: Update Meta Core
on: 
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag of Clash Meta, such as Prerelease-Alpha, Prerelease-Beta, v1.11.1'
        required: true
        type: string
env:
  download_tag: ${{ github.event.inputs.tag }}
  download_version: ''
  download_url: https://github.com/MetaCubeX/Clash.Meta/releases/download
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main
    - name: Init Dependencies
      run: |
        wget https://github.com/upx/upx/releases/download/v3.96/upx-3.96-amd64_linux.tar.xz
        wget https://github.com/upx/upx/releases/download/v3.93/upx-3.93-amd64_linux.tar.xz
        tar xf upx-3.96-amd64_linux.tar.xz
        tar xf upx-3.93-amd64_linux.tar.xz
    - name: Download Core
      run: |
        download_version=${download_tag}
        echo "download_version=${download_version}" >> ${GITHUB_ENV}
        archs=(armv7)
        new_name=(armv7)
        mkdir tmp
        for((i=0;i<1;i++));do
          wget "https://github.com/MetaCubeX/Clash.Meta/releases/download/v1.15.1/clash.meta-linux-armv7-v1.15.1.gz" -O - | gunzip -c > ./tmp/clash-linux-${new_name[i]}
          chmod +x ./tmp/clash-linux-${new_name[i]}
          if [ "${archs[i]}" != "armv5" ];then
            if [[ ${archs[i]} = mips* ]];then
              ./upx-3.93-amd64_linux/upx ./tmp/clash-linux-${new_name[i]}
            else
              ./upx-3.96-amd64_linux/upx ./tmp/clash-linux-${new_name[i]}
            fi
          fi
        done
        rm -fr upx*
    - name: Update
      run: |
        rm -fr ./bin/clash.meta/*
        cp ./tmp/* ./bin/clash.meta/
        rm -fr ./tmp
        sed -i "s/meta_v=.*/meta_v=$(./bin/clash.meta/clash-linux-amd64 -v 2>/dev/null | head -n 1 | sed 's/ linux.*//;s/.* //')/" bin/version
    - name: Commit and push
      run: |
        git config --global user.email "liwangcp@gmail.com" && git config --global user.name "Bot"
        git add . && git commit -m "更新Meta内核至${download_version}" || exit 0
        git push
    - name: Cleanup Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2      
